In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [ ]:
train.head(10)

id        date country              store             product  num_sold
0   0  2010-01-01  Canada  Discount Stickers   Holographic Goose       NaN
1   1  2010-01-01  Canada  Discount Stickers              Kaggle     973.0
2   2  2010-01-01  Canada  Discount Stickers        Kaggle Tiers     906.0
3   3  2010-01-01  Canada  Discount Stickers            Kerneler     423.0
4   4  2010-01-01  Canada  Discount Stickers  Kerneler Dark Mode     491.0
5   5  2010-01-01  Canada  Stickers for Less   Holographic Goose     300.0
6   6  2010-01-01  Canada  Stickers for Less              Kaggle    1837.0
7   7  2010-01-01  Canada  Stickers for Less        Kaggle Tiers    1659.0
8   8  2010-01-01  Canada  Stickers for Less            Kerneler     807.0
9   9  2010-01-01  Canada  Stickers for Less  Kerneler Dark Mode     940.0

In [ ]:
train.shape

(230130, 6)

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230130 entries, 0 to 230129
Data columns (total 6 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   id        230130 non-null  int64  
 1   date      230130 non-null  object 
 2   country   230130 non-null  object 
 3   store     230130 non-null  object 
 4   product   230130 non-null  object 
 5   num_sold  221259 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 10.5+ MB


In [ ]:
train.describe()

id       num_sold
count  230130.000000  221259.000000
mean   115064.500000     752.527382
std     66432.953062     690.165445
min         0.000000       5.000000
25%     57532.250000     219.000000
50%    115064.500000     605.000000
75%    172596.750000    1114.000000
max    230129.000000    5939.000000

In [ ]:
train.isnull().sum()

id             0
date           0
country        0
store          0
product        0
num_sold    8871
dtype: int64

In [ ]:
test.isnull().sum()

id         0
date       0
country    0
store      0
product    0
dtype: int64

In [ ]:
train['num_sold']=train['num_sold'].fillna(train['num_sold'].mode()[0])

In [ ]:
train.nunique()

id          230130
date          2557
country          6
store            3
product          5
num_sold      4037
dtype: int64

In [ ]:
train.drop(['id','date'],axis=1,inplace=True)

In [ ]:
train.head()

country              store             product  num_sold
0  Canada  Discount Stickers   Holographic Goose       5.0
1  Canada  Discount Stickers              Kaggle     973.0
2  Canada  Discount Stickers        Kaggle Tiers     906.0
3  Canada  Discount Stickers            Kerneler     423.0
4  Canada  Discount Stickers  Kerneler Dark Mode     491.0

In [ ]:
X=train.iloc[:,:-1].values
y=train.iloc[:,-1].values

In [ ]:
print(X)

[['Canada' 'Discount Stickers' 'Holographic Goose']
 ['Canada' 'Discount Stickers' 'Kaggle']
 ['Canada' 'Discount Stickers' 'Kaggle Tiers']
 ...
 ['Singapore' 'Premium Sticker Mart' 'Kaggle Tiers']
 ['Singapore' 'Premium Sticker Mart' 'Kerneler']
 ['Singapore' 'Premium Sticker Mart' 'Kerneler Dark Mode']]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,1] = le.fit_transform(X[:,1])

In [ ]:
print(X)

[['Canada' 0 'Holographic Goose']
 ['Canada' 0 'Kaggle']
 ['Canada' 0 'Kaggle Tiers']
 ...
 ['Singapore' 1 'Kaggle Tiers']
 ['Singapore' 1 'Kerneler']
 ['Singapore' 1 'Kerneler Dark Mode']]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)


[[1.0 0.0 0.0 ... 0.0 0 'Holographic Goose']
 [1.0 0.0 0.0 ... 0.0 0 'Kaggle']
 [1.0 0.0 0.0 ... 0.0 0 'Kaggle Tiers']
 ...
 [0.0 0.0 0.0 ... 1.0 1 'Kaggle Tiers']
 [0.0 0.0 0.0 ... 1.0 1 'Kerneler']
 [0.0 0.0 0.0 ... 1.0 1 'Kerneler Dark Mode']]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [7])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 0.0 0.0 0]
 [0.0 1.0 0.0 ... 0.0 0.0 0]
 [0.0 0.0 1.0 ... 0.0 0.0 0]
 ...
 [0.0 0.0 1.0 ... 0.0 1.0 1]
 [0.0 0.0 0.0 ... 0.0 1.0 1]
 [0.0 0.0 0.0 ... 0.0 1.0 1]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_val = sc.transform(X_val)

In [ ]:
!pip install scikit-learn==1.1.2 xgboost

In [ ]:
from xgboost import XGBRegressor
regressor = XGBRegressor()
regressor.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [ ]:
y_pred =regressor.predict(X_val)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_val, y_pred)

0.9429530228149631

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=regressor,X=X_train,y=y_train,cv=10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))

Accuracy: 94.28 %


In [ ]:
test.head()

id        date country              store             product
0  230130  2017-01-01  Canada  Discount Stickers   Holographic Goose
1  230131  2017-01-01  Canada  Discount Stickers              Kaggle
2  230132  2017-01-01  Canada  Discount Stickers        Kaggle Tiers
3  230133  2017-01-01  Canada  Discount Stickers            Kerneler
4  230134  2017-01-01  Canada  Discount Stickers  Kerneler Dark Mode

In [ ]:
test_ids=test['id']

In [ ]:
test.drop(['id','date'],axis=1,inplace=True)

In [ ]:
X_test=test.iloc[:,:].values

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_test[:,1] = le.fit_transform(X_test[:,1])

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X_test = np.array(ct.fit_transform(X_test))

In [ ]:
print(X_test)

[[1.0 0.0 0.0 ... 0.0 0 'Holographic Goose']
 [1.0 0.0 0.0 ... 0.0 0 'Kaggle']
 [1.0 0.0 0.0 ... 0.0 0 'Kaggle Tiers']
 ...
 [0.0 0.0 0.0 ... 1.0 1 'Kaggle Tiers']
 [0.0 0.0 0.0 ... 1.0 1 'Kerneler']
 [0.0 0.0 0.0 ... 1.0 1 'Kerneler Dark Mode']]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [7])], remainder='passthrough')
X_test = np.array(ct.fit_transform(X_test))

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_test = sc.fit_transform(X_test)

In [ ]:
submission_preds=regressor.predict(X_test)

In [ ]:
df=pd.DataFrame({'id':test_ids.values,'num_sold':submission_preds})

In [ ]:
# df.to_csv('prediction5.csv',index=False)